import { Island } from '@/components/island'
import type { Metadata } from 'next'
import { ShoppingBagIsland } from './shopping-bag'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function StoreLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div className="pb-16">
      {children}
      <Island>
        <ShoppingBagIsland />
      </Island>
    </div>
  )
}
