import { Island } from '@/components/island'
import type { Metadata } from 'next'

import { Search } from './search'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function StoreLayout({
  header,
  promotions,
  topSellers,
  productsList,
  bagIsland,
}: {
  header: React.ReactNode
  promotions: React.ReactNode
  topSellers: React.ReactNode
  productsList: React.ReactNode
  bagIsland: React.ReactNode
}) {
  return (
    <main className="pb-20">
      {header}

      <Search />

      {promotions}

      {topSellers}

      {productsList}

      <Island>{bagIsland}</Island>
    </main>
  )
}
