import { Metadata } from 'next'
import { getStores } from './actions'
import NotFound from './not-found'

export const metadata: Metadata = {
  title: 'Ztore',
  description: 'Generated by create next app',
}

export default async function PublicStoreLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode
  params: { public_store: string }
}>) {
  const storeSlug = params.public_store.split('-')
  const storeName = storeSlug.join(' ')

  const { stores, error } = await getStores(storeName)

  if (error) {
    console.log(error)
  }

  if (stores && stores.length === 0) {
    return <NotFound />
  }
  return <div>{children}</div>
}
