import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Ztore',
  description: 'Generated by create next app',
}

export default async function PublicStoreLayout({
  children,
  searchParams,
}: Readonly<{
  children: React.ReactNode
  searchParams: { public_store: string }
}>) {
  return <div>{children}</div>
}
