import { Island } from '@/components/island'
import { Navigation } from '@/components/navigation'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function ProtectedLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div className="pb-16 md:flex flex-row">
      <Island>
        <Navigation />
      </Island>

      {children}
    </div>
  )
}
