import { Island } from '@/components/island'
import { Navigation } from '@/components/navigation'
import { createClient } from '@/lib/supabase/server'
import { readRows } from '@/services/supabase-service'
import type { Metadata } from 'next'
import { redirect } from 'next/navigation'

export const metadata: Metadata = {
  title: 'Ztore | Admin',
  description: 'Generated by create next app',
}

export default async function ProtectedLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const supabase = createClient()

  const { data: userData, error: userError } = await supabase.auth.getUser()

  if (userError || !userData?.user) {
    redirect('/admin/sign-in')
  }

  const { data, error } = await readRows({
    route: 'users',
    filter: {
      key: 'email',
      value: userData?.user.email ?? '',
    },
  })

  if (!error && data?.length === 0) {
    return redirect('/admin/onboarding')
  }

  return (
    <main className="pb-16 md:flex flex-row">
      <Island>
        <Navigation />
      </Island>

      {children}
    </main>
  )
}
