import { Island } from '@/components/island'
import { Navigation } from '@/components/navigation'
import { createClient } from '@/lib/supabase/server'
import type { Metadata } from 'next'
import { redirect } from 'next/navigation'

export const metadata: Metadata = {
  title: 'Ztore | Admin',
  description: 'Generated by create next app',
}

export default async function ProtectedLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const supabase = createClient()

  const { data, error } = await supabase.auth.getUser()
  if (error || !data?.user) {
    redirect('/admin/sign-in')
  }

  return (
    <div className="pb-16 md:flex flex-row">
      <Island>
        <Navigation />
      </Island>

      {children}
    </div>
  )
}
