export const statuses = {
  pending: {
    status: 'Pendente',
    next_step: 'Aguardando confirmação do pedido.',
    delivery_address: 'O seu pedido será entregue',
    color: 'bg-blue-500',
    next_status: 'preparing',
    action_text: 'Aprovar pedido',
  },
  preparing: {
    status: 'Em preparo',
    next_step: 'Preparando o pedido.',
    delivery_address: 'O seu pedido será entregue',
    color: 'bg-yellow-500',
    next_status: 'shipped',
    action_text: 'Despachar pedido',
  },
  shipped: {
    status: 'Despachado',
    next_step: 'Pedido a caminho.',
    delivery_address: 'O seu pedido será entregue',
    color: 'bg-blue-500',
    next_status: 'delivered',
    action_text: 'Marcar como Entregue',
  },
  delivered: {
    status: 'Entregue',
    next_step: 'Pedido entregue ao cliente.',
    delivery_address: 'O seu pedido foi entregue',
    color: 'bg-green-500',
    next_status: null,
    action_text: null,
  },
  cancelled: {
    status: 'Cancelado',
    next_step: 'Pedido cancelado.',
    delivery_address: 'O pedido não será entregue.',
    color: 'bg-red-500',
    next_status: null,
    action_text: null,
  },
}
