export const statuses = {
  pending: {
    status: 'Pendente',
    next_step: 'Aguardando pagamento.',
    delivery_address: 'O seu pedido será entregue',
    color: 'bg-blue-500',
    next_status: 'awaiting_payment',
    action_text: 'Marcar como Aguardando Pagamento',
  },
  processing: {
    status: 'Processando',
    next_step: 'Processando pedido.',
    delivery_address: 'O seu pedido será entregue',
    color: 'bg-blue-500',
    next_status: 'approved',
    action_text: 'Marcar como Aprovado',
  },
  approved: {
    status: 'Aprovado',
    next_step: 'Preparando para envio.',
    delivery_address: 'O seu pedido será entregue',
    color: 'bg-green-500',
    next_status: 'preparing',
    action_text: 'Marcar como Em Preparo',
  },
  preparing: {
    status: 'Em preparo',
    next_step: 'Preparando para envio.',
    delivery_address: 'O seu pedido será entregue',
    color: 'bg-blue-500',
    next_status: 'picking',
    action_text: 'Marcar como Em Separação',
  },
  picking: {
    status: 'Em Separação',
    next_step: 'Separando para envio.',
    delivery_address: 'O seu pedido será entregue',
    color: 'bg-blue-500',
    next_status: 'shipped',
    action_text: 'Marcar como Despachado',
  },
  shipped: {
    status: 'Despachado',
    next_step: 'Pedido a caminho.',
    delivery_address: 'O seu pedido será entregue',
    color: 'bg-blue-500',
    next_status: 'delivered',
    action_text: 'Marcar como Entregue',
  },
  delivered: {
    status: 'Entregue',
    next_step: 'Pedido entregue.',
    delivery_address: 'O seu pedido foi entregue',
    color: 'bg-green-500',
    next_status: null,
    action_text: null,
  },
  cancelled: {
    status: 'Cancelado',
    next_step: 'Pedido cancelado. Entre em contato para mais informações.',
    delivery_address: 'O pedido não será entregue.',
    color: 'bg-red-500',
    next_status: null,
    action_text: null,
  },
  returned: {
    status: 'Devolvido',
    next_step: 'Devolução confirmada. Aguarde o reembolso.',
    delivery_address: 'A devolução foi confirmada.',
    color: 'bg-red-500',
    next_status: 'refunded',
    action_text: 'Marcar como Reembolsado',
  },
  refunded: {
    status: 'Reembolsado',
    next_step: 'Reembolso realizado.',
    delivery_address: 'O valor pago foi devolvido.',
    color: 'bg-green-500',
    next_status: null,
    action_text: null,
  },
  payment_failed: {
    status: 'Falha no Pagamento',
    next_step: 'Falha no pagamento. Tente novamente.',
    delivery_address:
      'O pedido não será processado devido a falha no pagamento.',
    color: 'bg-red-500',
    next_status: 'pending',
    action_text: 'Marcar como Pendente',
  },
  awaiting_payment: {
    status: 'Aguardando Pagamento',
    next_step: 'Aguardando confirmação de pagamento.',
    delivery_address:
      'O pedido será processado após a confirmação do pagamento.',
    color: 'bg-blue-500',
    next_status: 'processing',
    action_text: 'Marcar como Processando',
  },
  under_review: {
    status: 'Em Análise',
    next_step: 'Pedido em análise.',
    delivery_address: 'O pedido está sendo revisado.',
    color: 'bg-blue-500',
    next_status: 'processing',
    action_text: 'Marcar como Processando',
  },
}
